export {default as logo} from './logo.png'
export {default as flag} from './flag.png'
export {default as settings} from './settings.png'
export {default as background} from './background.png'
export {default as Rectangle2} from './Rectangle2.png'
export {default as Rectangle1} from './Rectangle1.png'
