export {default as Projects} from './Projects/Projects'
export {default as Configurations} from './Configurations/Configurations'
export{default as ProjectView} from './ProjectView/ProjectView'
export {default as Employees} from './Employees/Employees'
export {default as EmployeeView} from './EmployeeView/EmployeeView'