export {default as Projects} from './Projects/Projects'
export {default as Configurations} from './Configurations/Configurations'
export{default as ProjectView} from './ProjectView/ProjectView'
export {default as Employees} from './Employees/Employees'
export {default as EmployeeView} from './EmployeeView/EmployeeView'
export {default as Login} from './Login/Login'
export {default as LoginRedirect} from './LoginRedirect/LoginRedirect'
export {default as ResetPassWord} from './ResetPassWord/ResetPassWord'
export {default as ForgetPassWord} from './ForgetPassWord/ForgotPassWord'